//USER
export const REGISTER = "REGISTER";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";

//SERVICES
export const GET_SERVICES = "GET_SERVICES";
export const CREATE_SERVICE = "CREATE_SERVICE";
export const EDIT_SERVICE = "EDIT_SERVICE";
export const DELETE_SERVICE = "DELETE_SERVICE";

//DISABLE DAYS
export const GET_DISABLE_DAYS = "GET_DISABLE_DAYS";
export const CREATE_DISABLE_DAY = "CREATE_DISABLE_DAY";
export const DELETE_DISABLE_DAY = "DELETE_DISABLE_DAY";

//RESERVATIONS
export const GET_ALL_RESERVATIONS = "GET_ALL_RESERVATIONS";
export const GET_RESERVATIONS_BY_GMAIL = "GET_RESERVATIONS_BY_GMAIL";
export const GET_RESERVATIONS_BY_WORKER = "GET_RESERVATIONS_BY_WORKER";
export const CREATE_RESERVATION = "CREATE_RESERVATION";
export const CHANGE_RESERVATION_STATUS = "CHANGE_RESERVATION_STATUS";
export const CANCEL_RESERVATION = "CANCEL_RESERVATION";

//WORKERS
export const GET_ALL_WORKERS = "GET_ALL_WORKERS";
export const GET_WORKER_BY_SERVICE = "GET_WORKER_BY_SERVICE";
export const CREATE_WORKER = "CREATE_WORKER";
export const EDIT_WORKER = "EDIT_WORKER";
export const DELETE_WORKER = "DELETE_WORKER";

//CALENDAR
export const GET_WORKING_HOURS_BY_DATE = "GET_WORKING_HOURS_BY_DATE";
export const GET_BLOQUED_DAYS = "GET_BLOQUED_DAYS";

//WORKING HOURS
export const GET_WORKING_HOURS_BY_WORKER = "GET_WORKING_HOURS_BY_WORKER";
export const CREATE_WORKING_HOURS = "CREATE_WORKING_HOURS";
export const EDIT_WORKING_HOURS = "EDIT_WORKING_HOURS";
export const DELETE_WORKING_HOURS = "DELETE_WORKING_HOURS";

//CUSTOM WORKING HOURS
export const GET_CUSTOM_WORKING_HOURS_BY_WORKER =
	"GET_CUSTOM_WORKING_HOURS_BY_WORKER";
export const CREATE_CUSTOM_WORKING_HOURS = "CREATE_CUSTOM_WORKING_HOURS";
export const EDIT_CUSTOM_WORKING_HOURS = "EDIT_CUSTOM_WORKING_HOURS";
export const DELETE_CUSTOM_WORKING_HOURS = "DELETE_CUSTOM_WORKING_HOURS";

//LOADINGS
export const SET_LOADING_SESSION = "SET_LOADING_SESSION";
export const SET_LOADING_SERVICES = "SET_LOADING_SERVICES";
export const SET_LOADING_RESERVATIONS = "SET_LOADING_RESERVATIONS";
export const SET_LOADING_WORKERS = "SET_LOADING_WORKERS";
export const SET_LOADING_DISABLE_DAYS = "SET_LOADING_DISABLE_DAYS";
export const SET_LOADING_WORKING_HOURS = "SET_LOADING_WORKING_HOURS";
export const SET_LOADING_CUSTOM_WORKING_HOURS =
	"SET_LOADING_CUSTOM_WORKING_HOURS";
export const SET_LOADING_BLOQUED_DAYS = "SET_LOADING_BLOQUED_DAYS";
export const SET_LOADING_WORKING_HOURS_BY_DATE =
	"SET_LOADING_WORKING_HOURS_BY_DATE";
